### PR TITLE
Update to Angular 7

### PR DESCRIPTION
**Pull request by mhosman**
In order to avoid: `npm WARN @nicky-lenaers/ngx-scroll-to@1.1.1 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.`

### CODE REVIEW

**Comment by nicky-lenaers** [comment]
@mhosman Does is still work with v6? Or should I use a major version bump?

**Comment by mhosman** [comment]
Is working but you get this warning all the time:
`npm WARN @nicky-lenaers/ngx-scroll-to@1.1.1 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by BergerLand** [comment]
What is going on with this PR?  It's a simple thing, why isn't it merged?

**Comment by nicky-lenaers** [comment]
All, I'm almost done upgrading the lib according to the Angular 7 library inclusion. Support will be added soon.

**Comment by nicky-lenaers** [comment]
Closing this in favor of #114 . Had to do some additional refactoring for the whole repository. Thanks for helping out!

Angular v7 is now suppored on [2.0.0](https://github.com/nicky-lenaers/ngx-scroll-to/releases/tag/2.0.0)

**Pull request closed without merging**
