### PR TITLE
Angular 6 Fix: Observable from rxjs

### PR DESCRIPTION
**Pull request by omrsmeh**
Observable fix in Angular 6

Basically library change in Angular 6 and I have patched it for change

### CODE REVIEW

**Comment by nicky-lenaers** [comment]
@omrsmeh I'm not familiar yet with the exact update paths for ng6. Would this break support for ng5 as a dependency?

**Comment by omrsmeh** [comment]
@nicky-lenaers yap it will break the support for ng5. We need to create a separate repository with to support ng6. As currently we don't have any repo which support ng6, so I have created a pull request in this repository.

**Comment by nicky-lenaers** [comment]
@omrsmeh: 

> We need to create a separate repository which support ng6.

I guess a tag would suffice here. I'm going to look into the full Angular Upgrade path soon, as I'm currently a little busy. Check back in a short while 👍

**Comment by yanis-git** [comment]
i have just seen your pull request after doing mine. 

https://github.com/nicky-lenaers/ngx-scroll-to/pull/88

let me know if you want to close mine, i will report my update here.

**Comment by nicky-lenaers** [comment]
@omrsmeh Thanks for this PR! I've transported some of these changes onto #88, so closing this one. Credits to you aswel!

**Pull request closed without merging**
