### PR TITLE
fix: scroll to element with relative positioned parent

### PR DESCRIPTION
**Pull request by izmaylovdev**

### CODE REVIEW

**Comment by rafa-as** [comment]
@nicky-lenaers please, can you merge this PR? Works properly and makes the library usable.

**Comment by izmaylovdev** [comment]
@rafa-as this project not maintained more, here is package with fix https://www.npmjs.com/package/izmaylovdev-ngx-scroll-to

**Comment by izmaylovdev** [comment]
image

**Comment by nicky-lenaers** [comment]
@rafa-as Unfortunately, this project is no longer maintained. I've updated the README.md to include this. Apologies for the inconvenience.

**Comment by rafa-as** [comment]
> @rafa-as Unfortunately, this project is no longer maintained. I've updated the README.md to include this. Apologies for the inconvenience.

Can you add some maintainers to continue the development?

**Comment by nicky-lenaers** [comment]
> > @rafa-as Unfortunately, this project is no longer maintained. I've updated the README.md to include this. Apologies for the inconvenience.
> 
> Can you add some maintainers to continue the development?

Sure! Who do you want me to add?

**Comment by rafa-as** [comment]
> > > @rafa-as Unfortunately, this project is no longer maintained. I've updated the README.md to include this. Apologies for the inconvenience.
> > 
> > 
> > Can you add some maintainers to continue the development?
> 
> Sure! Who do you want me to add?

Me and maybe @izmaylovdev also wants

**Pull request merged**
