### PR TITLE
feat(lib): support for angular v13

### PR DESCRIPTION
**Pull request by Jonnyprof**
refactor: replace tslint with eslint
refactor: change protractor to cypress
build: update third party libraries

### CODE REVIEW

**Comment by igorlino** [comment]
@nicky-lenaers Could please take this up?

**Comment by rafa-as** [comment]
> @nicky-lenaers Could please take this up?

I will merge this PR and publish the new version ASAP

**Comment by HarelM** [comment]
Thanks @rafa-as!

**Comment by igorlino** [comment]
@Jonnyprof any change to include angular v14 support?

**Comment by nicky-lenaers** [comment]
Thanks @rafa-as , I am not actively maintaining this package anymore

**Comment by andreas-aeschlimann** [comment]
> Thanks @rafa-as , I am not actively maintaining this package anymore

Would you mind signing it over? The package is still very popular and useful to many people.

BTW: I wrote you a mail some months ago about it, but haven't received a reply yet.

**Comment by nicky-lenaers** [comment]
@andreas-aeschlimann Thanks for your reply. I must have overlooked your email (still can't find it though), sorry for that. I added you as a collaborator to this repo. Is this sufficient for you to continue?

**Comment by rafa-as** [comment]
We are working to make the v14 version compatible also

**Comment by andreas-aeschlimann** [comment]
> @andreas-aeschlimann Thanks for your reply. I must have overlooked your email (still can't find it though), sorry for that. I added you as a collaborator to this repo. Is this sufficient for you to continue?

Don't worry, it wasn't that important (logs say it was on Mar 23, 23:51).

Thank you for your quick reply. If @rafa-as wants to help, maybe you can add him as well?

The only question that remains is how we are going to publish it. If we want to continue to use the current NPM repository, you would need to give us access there as well (it seems to be simple and possible on a per-repo basis). Otherwise we would need to start a fork.

**Comment by rafa-as** [comment]
> > @andreas-aeschlimann Thanks for your reply. I must have overlooked your email (still can't find it though), sorry for that. I added you as a collaborator to this repo. Is this sufficient for you to continue?
> 
> Don't worry, it wasn't that important (logs say it was on Mar 23, 23:51).
> 
> Thank you for your quick reply. If @rafa-as wants to help, maybe you can add him as well?
> 
> The only question that remains is how we are going to publish it. If we want to continue to use the current NPM repository, you would need to give us access there as well (it seems to be simple and possible on a per-repo basis). Otherwise we would need to start a fork.

@andreas-aeschlimann I have npm permissions to publish new versions ;)

**Comment by andreas-aeschlimann** [comment]
> > > @andreas-aeschlimann Thanks for your reply. I must have overlooked your email (still can't find it though), sorry for that. I added you as a collaborator to this repo. Is this sufficient for you to continue?
> > 
> > 
> > Don't worry, it wasn't that important (logs say it was on Mar 23, 23:51).
> > Thank you for your quick reply. If @rafa-as wants to help, maybe you can add him as well?
> > The only question that remains is how we are going to publish it. If we want to continue to use the current NPM repository, you would need to give us access there as well (it seems to be simple and possible on a per-repo basis). Otherwise we would need to start a fork.
> 
> @andreas-aeschlimann I have npm permissions to publish new versions ;)

Ah, great. I think the most important thing is that we have a release for each Angular version (if necessary). I'll be available if you need support.

**Comment by mparpaillon** [comment]
Hey all. Can we merge and publish this to npm? Looks like the PR is ready

**Comment by dxs0319** [comment]
> Hey all. Can we merge and publish this to npm? Looks like the PR is ready

Yes please! Would greatly appreciate it @rafa-as

**Comment by almoral** [comment]
@rafa-as Is there any timeline for merging this PR? It would be immensely helpful!

**Comment by andreas-aeschlimann** [comment]
@rafa-as, is there a specific reason why we are waiting with the update? I would do it, unfortunately I only received permissions for this repo and not for NPM. We should really publish the update, Angular 14 is already out as well.

**Comment by TheDelta** [comment]
Whats the holdup now? :)

**Comment by TheDelta** [comment]
@andreas-aeschlimann @rafa-as I think many would appreciate an answer ;)

@nicky-lenaers in case of no response, should someone else take over, including going through open issues and clean things up?

**Comment by nicky-lenaers** [comment]
@TheDelta Sure, let me know if you're interested:-)

**Comment by TheDelta** [comment]
Thanks for the good news! Looking forward to it 🚀 ❤️

**Comment by andreas-aeschlimann** [comment]
> To @TheDelta and the others, I'm so sorry about the silence, for personal reasons I couldn't resolve this PR and the other issues. We are working to finally merge this PR, publish the version and create a new PR for the v14 version, the last one supporting non-ivy compilations.
> 
> Thanks for your patience!

Thanks @rafa-as. Is it just a matter of merging and publishing, or is there still work to do? As I have been added to this repo just recently, I didn't want to go ahead and do it without your feedback. I would happily do it if I got the "clearance" from you guys.

**Comment by nicky-lenaers** [comment]
@andreas-aeschlimann Please go ahead

**Review by rafa-as — APPROVED** [review]

**Pull request merged**
